### ISSUE TITLE
no need for save exit words on large screens

### ISSUE THREAD

**Issue by Wladefant** [personalizedrefrigerator/js-draw#28]
Hey, first of all nicely done. The latency is just astronimical and not at all worse than samsung notes (which IS the best pen note taking app). I hope you understand the implications when joplin and js draw are tightly integrated, namely best overall note taking app for every group of people.

But now to the issue. 
I see the design choice to have the save and exit text when having a small screen 
![image](https://github.com/personalizedrefrigerator/js-draw/assets/79611093/0bd048fb-1330-48fe-8036-0fa7d51bd82e)
, but there is no need for that in bigger screen where everything is on one line and therefore lots of space is used by just text. just the icons will be enough.

I now see that that is already the case when the text does not fit 
![image](https://github.com/personalizedrefrigerator/js-draw/assets/79611093/2e575403-dc23-401b-b924-28c318e1c5bf)

All right then, then the solution is alright i suppose even though the text is not needed even if the screen is big enough. We should better add more toolbars

P.S. Is it alright if i report the joplin js draw bugs/features here?

**Comment by personalizedrefrigerator** [comment]
At present, it's possible to get the toolbar to look like this:
![screenshot: toolbar: Two lines, second line has a large amount of space on both sides](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/b976f471-56ab-48b0-90ec-ee07b3553c28)

Here are some options:
1. Increase the size of the buttons to fill available space
    - ![screenshot: toolbar with two lines. Second line has larger (stretched) buttons than the previous screenshot.](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/c8865537-5efe-44b4-99b2-9d341497e028)
2. Move both toolbar sections to the same line starting at a smaller screen width (e.g. sizes ≥ 550px instead of sizes ≥ 610px).
    - ![screenshot: toolbar with one line. Buttons that were on the first line in the previous screenshot are now on the left of the screen and have smaller text.](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/3cd4d6c4-b4e8-462b-8825-3c61558c2c86)

> P.S. Is it alright if i report the joplin js draw bugs/features here?

Reporting bugs/requesting features here is fine.

**Comment by Wladefant** [comment]
Yes, I only later realized that the text is only shown on a bigger screen when there is space. I am of the opinion that the bigger screen does not need the text, EVEN IF there is enough space, but we should better other tools that are normally hidden, though it is of course not an important point for sure. 

On an unrelated note: I would suggest adding feature requests in the github discussions section, as it now has almost all features of github issues and also some additional specifically for "Discussions". In the next day i will write a little feature request, so that we can use yaml Templates when filing bug reports and feature requests. 

P.S: The new jsdraw joplin are rather difficult to find. Where are they even located? I would suggest adding them to the joplin readme and definitely jsdraw readme for testing purposes

**Comment by personalizedrefrigerator** [comment]
Partially addressed in https://github.com/personalizedrefrigerator/js-draw/commit/f85d4593539e844e114e04d65b70cc4ea18190a5

**Comment by personalizedrefrigerator** [comment]
> On an unrelated note: I would suggest adding feature requests in the github discussions section, as it now has almost all features of github issues and also some additional specifically for "Discussions".

I've done this! "Ideas" has been renamed to "Ideas & Feature requests".

> In the next day i will write a little feature request, so that we can use yaml Templates when filing bug reports and feature requests.

That would be welcome!

**Comment by personalizedrefrigerator** [comment]
I'm closing this as addressed in https://github.com/personalizedrefrigerator/js-draw/commit/f85d4593539e844e114e04d65b70cc4ea18190a5. If it's still an issue, feel free to re-open it.
