### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Mr-Kanister** [personalizedrefrigerator/js-draw#6]
# Language name in English
German

# Translations
Please translate each of the strings in the right column (everything after the `: `) into the target language.

Ignore the surrounding single quotes. For example, to translate `insertDrawing: 'Insert Drawing',` to Spanish, please replace it with `insertDrawing: 'Añada dibujo',`.

If you're updating an existing translation, please only include the strings you're translating. Similarly, if you don't want to provide localizations for an entire language, only include the strings you did translate.

	pen: "Stift"
	eraser: "Radierer"
	select: "Auswahl"
	handTool: "Verschieben"
	zoom: "Vergrößerung"
	resetView: "Ansicht zurücksetzen"
	thicknessLabel: "Dicke: "
	colorLabel: "Farbe: "
	fontLabel: "Schriftart: "
	resizeImageToSelection: "Bildgröße an Auswahl anpassen"
	deleteSelection: "Auswahl löschen"
	duplicateSelection: "Auswahl duplizieren"
	undo: "Rückgangig"
	redo: "Wiederholen"
	selectObjectType: "Objekt-Typ: "
	pickColorFromScreen: "Farbe von Bildschirm auswählen"
	clickToPickColorAnnouncement: "Klicke auf den Bildschirm, um eine Farbe auszuwählen"
	selectionToolKeyboardShortcuts: "Auswahl-Werkzeug: Verwende die Pfeiltasten, um ausgewählte Elemente zu verschieben und ‚i‘ und ‚o‘, um die Größe zu ändern."
	touchPanning: "Ansicht mit Touchscreen verschieben"
	anyDevicePanning: "Ansicht mit jedem Eingabegerät verschieben"
	freehandPen: "Freihand"
	arrowPen: "Pfeil"
	linePen: "Linie"
	outlinedRectanglePen: "Umrissenes Rechteck"
	filledRectanglePen: "Ausgefülltes Rechteck"
	dropdownShown: t=>`Dropdown-Menü für ${t} angezeigt`
	dropdownHidden: t=>`Dropdown-Menü für ${t} versteckt`
	zoomLevel: t=>`Vergößerung: ${t}%`
	colorChangedAnnouncement: t=>`Farbe zu ${t} geändert`
	penTool: t=>`Stift ${t}`
	selectionTool: "Auswahl"
	eraserTool: "Radiergummi"
	touchPanTool: "Ansicht mit Touchscreen verschieben"
	twoFingerPanZoomTool: "Ansicht verschieben und vergrößern"
	undoRedoTool: "Rückgängig/Wiederholen"
	rightClickDragPanTool: "Rechtsklick-Ziehen"
	pipetteTool: "Farbe von Bildschirm auswählen
	keyboardPanZoom: "Tastaturkürzel zum Verschieben/Vergrößern der Ansicht"
	textTool: "Text"
	enterTextToInsert: "Einzufügender Text"
	toolEnabledAnnouncement: t=>`${t} aktiviert`
	toolDisabledAnnouncement: t=>`${t} deaktiviert`
	updatedViewport: "Transformierte Ansicht"
	transformedElements: t=>`${t} Element${1===t?"":"e"} transformiert`
	resizeOutputCommand: t=>`Bildgröße auf ${t.w}x${t.h} geändert`
	addElementAction: t=>`${t} hinzugefügt`
	eraseAction: (t,e)=>`Erased ${e} ${t}`
	duplicateAction: (t,e)=>`Duplicated ${e} ${t}`
	inverseOf: t=>`Umkehrung von ${t}`
	elements: "Elemente"
	erasedNoElements: "Nichts entfernt"
	duplicatedNoElements: "Nichts dupliziert"
	rotatedBy: t=>`${Math.abs(t)} Grad ${t<0?"im Uhrzeigersinn":"gegen den Uhrzeigersinn"} gedreht`
	movedLeft: "Nacht links bewegt"
	movedUp: "Nacht oben bewegt"
	movedDown: "Nacht unten bewegt"
	movedRight: "Nacht rechts bewegt"
	zoomedOut: "Ansicht verkleinert"
	zoomedIn: "Ansicht vergrößert"
	selectedElements: t=>`${t} Element${ 1===t ? "" : "e" } ausgewählt`
	stroke: "Strich"
	svgObject: "SVG-Objekt"
	text: t=>`Text-Objekt: ${t}`
	pathNodeCount: t=>`Es gibt ${t} sichtbare Pfad-Objekte.`
	textNodeCount: t=>`Es gibt ${t} sichtbare Text-Knotenpunkte.`
	textNode: t=>`Text: ${t}`
	rerenderAsText: "Als Text darstellen"
	accessibilityInputInstructions: "Drücke ‚t‘, um den Inhalt des Ansichtsfensters als Text zu lesen. Verwende die Pfeiltasten, um die Ansicht zu verschieben, und klicke und ziehe, um Striche zu zeichnen. Drücke ‚w‘ zum Vergrößern und ‚s‘ zum Verkleinern der Ansicht."
	loading: t=>`Laden ${t}%...`
	imageEditor: "Bild-Editor"
	doneLoading: "Laden fertig"
	undoAnnouncement: t=>`Rückgangig gemacht ${t}`
	redoAnnouncement: t=>`Wiederholt ${t}`

**Comment by Mr-Kanister** [comment]
Why are there two variables at `eraseAction and` duplicateAction`?
If I know the context of both, I can translate them. Then I will make a pull request.

Best Regards

**Comment by personalizedrefrigerator** [comment]
> Why are there two variables at `eraseAction` and `duplicateAction`? If I know the context of both, I can translate them. Then I will make a pull request.
> 
> Best Regards

https://github.com/personalizedrefrigerator/js-draw/blob/175e2ed3f1b797f92bae40605848c3d63b65ba20/src/commands/localization.ts#L17-L20

Thank you for working on this! I didn't notice the need for variable names in the template.

**Comment by Mr-Kanister** [comment]
Ah, so it is displaying, how much items it is duplicating or erasing at once and of what type the items are, right?

I'm fine with a pull request 👍🏼 :)

**Comment by personalizedrefrigerator** [comment]
> Ah, so it is displaying, how much items it is duplicating or erasing at once and of what type the items are, right?

Yes -- it's used as a screen reader announcement after clicking the "duplicate" or "delete" buttons when things are selected (e.g. selecting three strokes, then clicking 'delete' would cause a screen reader to announce "Erased 3 strokes.")

**Comment by Mr-Kanister** [comment]
Alright, perfekt:

```
pen: "Stift"
eraser: "Radierer"
select: "Auswahl"
handTool: "Verschieben"
zoom: "Vergrößerung"
resetView: "Ansicht zurücksetzen"
thicknessLabel: "Dicke: "
colorLabel: "Farbe: "
fontLabel: "Schriftart: "
resizeImageToSelection: "Bildgröße an Auswahl anpassen"
deleteSelection: "Auswahl löschen"
duplicateSelection: "Auswahl duplizieren"
undo: "Rückgängig"
redo: "Wiederholen"
selectObjectType: "Objekt-Typ: "
pickColorFromScreen: "Farbe von Bildschirm auswählen"
clickToPickColorAnnouncement: "Klicke auf den Bildschirm, um eine Farbe auszuwählen"
selectionToolKeyboardShortcuts: "Auswahl-Werkzeug: Verwende die Pfeiltasten, um ausgewählte Elemente zu verschieben und ‚i‘ und ‚o‘, um ihre Größe zu ändern."
touchPanning: "Ansicht mit Touchscreen verschieben"
anyDevicePanning: "Ansicht mit jedem Eingabegerät verschieben"
freehandPen: "Freihand"
arrowPen: "Pfeil"
linePen: "Linie"
outlinedRectanglePen: "Umrissenes Rechteck"
filledRectanglePen: "Ausgefülltes Rechteck"
dropdownShown: t=>`Dropdown-Menü für ${t} angezeigt`
dropdownHidden: t=>`Dropdown-Menü für ${t} versteckt`
zoomLevel: t=>`Vergößerung: ${t}%`
colorChangedAnnouncement: t=>`Farbe zu ${t} geändert`
penTool: t=>`Stift ${t}`
selectionTool: "Auswahl"
eraserTool: "Radiergummi"
touchPanTool: "Ansicht mit Touchscreen verschieben"
twoFingerPanZoomTool: "Ansicht verschieben und vergrößern"
undoRedoTool: "Rückgängig/Wiederholen"
rightClickDragPanTool: "Rechtsklick-Ziehen"
pipetteTool: "Farbe von Bildschirm auswählen
keyboardPanZoom: "Tastaturkürzel zum Verschieben/Vergrößern der Ansicht"
textTool: "Text"
enterTextToInsert: "Einzufügender Text"
toolEnabledAnnouncement: t=>`${t} aktiviert`
toolDisabledAnnouncement: t=>`${t} deaktiviert`
updatedViewport: "Transformierte Ansicht"
transformedElements: t=>`${t} Element${1===t?"":"e"} transformiert`
resizeOutputCommand: t=>`Bildgröße auf ${t.w}x${t.h} geändert`
addElementAction: t=>`${t} hinzugefügt`
eraseAction: (t,e)=>`${e} ${t} gelöscht`
duplicateAction: (t,e)=>`${e} ${t} dupliziert`
inverseOf: t=>`Umkehrung von ${t}`
elements: "Elemente"
erasedNoElements: "Nichts entfernt"
duplicatedNoElements: "Nichts dupliziert"
rotatedBy: t=>`${Math.abs(t)} Grad ${t<0?"im Uhrzeigersinn":"gegen den Uhrzeigersinn"} gedreht`
movedLeft: "Nacht links bewegt"
movedUp: "Nacht oben bewegt"
movedDown: "Nacht unten bewegt"
movedRight: "Nacht rechts bewegt"
zoomedOut: "Ansicht verkleinert"
zoomedIn: "Ansicht vergrößert"
selectedElements: t=>`${t} Element${ 1===t ? "" : "e" } ausgewählt`
stroke: "Strich"
svgObject: "SVG-Objekt"
text: t=>`Text-Objekt: ${t}`
pathNodeCount: t=>`Es gibt ${t} sichtbare Pfad-Objekte.`
textNodeCount: t=>`Es gibt ${t} sichtbare Text-Knotenpunkte.`
textNode: t=>`Text: ${t}`
rerenderAsText: "Als Text darstellen"
accessibilityInputInstructions: "Drücke ‚t‘, um den Inhalt des Ansichtsfensters als Text zu lesen. Verwende die Pfeiltasten, um die Ansicht zu verschieben, und klicke und ziehe, um Striche zu zeichnen. Drücke ‚w‘ zum Vergrößern und ‚s‘ zum Verkleinern der Ansicht."
loading: t=>`Laden ${t}%...`
imageEditor: "Bild-Editor"
doneLoading: "Laden fertig"
undoAnnouncement: t=>`Rückgangig gemacht ${t}`
redoAnnouncement: t=>`Wiederholt ${t}`
```

**Comment by Mr-Kanister** [comment]
Nvm, please do a commit yourself, I thought it would be as easy as in the Joplin Plugin ;)
Thanks!

**Comment by personalizedrefrigerator** [comment]
The commit has been pushed!

https://github.com/personalizedrefrigerator/js-draw/commit/1e5bdf561d9c5eb6bf57a07d929c098103d3e3b6
