### ISSUE TITLE
Bug: Pen Type Icons 

### ISSUE THREAD

**Issue by awmasakityan** [personalizedrefrigerator/js-draw#87]
### Describe the issue

Flat, Round, and Polyline Pen Types share the same icon.

![Screenshot 2024-11-25 221418](https://github.com/user-attachments/assets/c156d31a-e70c-43fb-b514-4b3a1d88ba50)

### Steps to reproduce the issue

import { Component, ElementRef,} from '@angular/core';
import { Editor,  makeEdgeToolbar  } from 'js-draw';
import { MaterialIconProvider } from '@js-draw/material-icons';
import { Bezier } from 'bezier-js';
import 'js-draw/bundledStyles';

@Component({
  selector: 'app-tldraw-canvas',
  templateUrl: './tldraw-canvas.component.html',
  styleUrls: ['./tldraw-canvas.component.scss']
})
export class TldrawCanvasComponent {

  constructor(private el: ElementRef) {}
  
  ngOnInit(): void {
    let canvas = document.querySelector('#canvas') as HTMLElement;
    
    if (canvas){
      const editor = new Editor(canvas, {
        iconProvider: new MaterialIconProvider(),
        wheelEventsEnabled: 'only-if-focused'
      });

      // Add a toolbar
      const toolbar = makeEdgeToolbar(editor);

      // ...with the default elements
      toolbar.addDefaults();
    }            
  }
}

here's my code

### Version information

v1.22.0

**Comment by personalizedrefrigerator** [comment]
This might happen if multiple copies of `js-draw` are included in the bundled application.

Currently, `@js-draw/material-icons` imports a copy of `js-draw` (which is a peer dependency) and uses it to determine the type of pen it's creating an icon for. If the copy of `js-draw` it imports is different from the copy that creates the editor, it won't recognize any of the pens and falls back to the default pen icon.

If you use NPM as a package manager, are there multiple different versions of `js-draw` in `package-lock.json`? If you use some other package manager are there multiple versions of `js-draw` in the workspace lockfile?

**Comment by awmasakityan** [comment]
I've executed the npm find-dupes and npm dedupe commands to identify and remove duplicate dependencies in my project. However, they did not resolve the issue with the pen type icons.

btw here's my package-lock.json
[package-lock.json](https://github.com/user-attachments/files/17910541/package-lock.json)

**Comment by personalizedrefrigerator** [comment]
Thank you for checking!

I've just released new versions of `js-draw` and `@js-draw/material-icons`.

The new `@js-draw/material-icons` version should allow providing a specific `js-draw` object. Does the following help?
1. Updating `@js-draw/material-icons`.
2. Changing the test code to
```ts
import { Component, ElementRef,} from '@angular/core';
import * as jsdraw from 'js-draw';
import { MaterialIconProvider, makeMaterialIconProviderClass } from '@js-draw/material-icons';
import { Bezier } from 'bezier-js';
import 'js-draw/bundledStyles';

const { Editor, makeEdgeToolbar } = jsdraw;
// Creates a MaterialIconProvider that uses a specific instance of the js-draw library:
const MaterialIconProvider = makeMaterialIconProviderClass(jsdraw);


@component({
  selector: 'app-tldraw-canvas',
  templateUrl: './tldraw-canvas.component.html',
  styleUrls: ['./tldraw-canvas.component.scss']
})
export class TldrawCanvasComponent {
  
  constructor(private el: ElementRef) {}
  
  ngOnInit(): void {
    let canvas = document.querySelector('#canvas') as HTMLElement;
    
    if (canvas){
      const editor = new Editor(canvas, {
        iconProvider: new MaterialIconProvider(),
        wheelEventsEnabled: 'only-if-focused'
      });
    
      // Add a toolbar
      const toolbar = makeEdgeToolbar(editor);
    
      // ...with the default elements
      toolbar.addDefaults();
    }            
  }
}
```

**Comment by awmasakityan** [comment]
Thanks a lot! Your solution has worked perfectly.

**Comment by awmasakityan** [comment]
Thanks a lot! Your solution has worked perfectly.
